export const COMPONENT_NAME = {
  SPLASH_SCREEN : 'SplashScreen',
  RESIDENCE : 'Residence',
  SIGN_IN : 'SignIn',
  PASSWORD_ENTRY : 'PasswordEntry',
  DASH_BOARD : 'DashBoard',
  MY_PROFILE : 'MyProfile',
  KYC_RESIDENCE_DETAILS : 'KycResidenceDetails',
  KYC_VERIFICATION : 'KycVerification',
  KYC_APPROVED : 'KycApproved',
  KYC_PRODUCTS : 'KycProducts',
  REMITTANCE : 'RamittanceScreen',
  MONEYSUCESS : 'MoneySuccess',
  SETPINWALLET : 'setPinWalletScreen',
  TRANSFER_MAIN : 'transferMain',
  IBAN_MAIN : 'IbanMain',
  IBAN_TRANSACTION : 'IbanTransaction',
  IBAN_CARD_DETAILS : 'IbanCardDetails',
  IBAN_SORT_TRANSACTION : 'IbanSortTransaction',
  IBAN_VIEW_STATEMENT : 'IbanViewStatement',
  BILL_PAYMENT :'billPayments',
  SET_MPIN : 'setMpinScreen',
  VALIDATE_MPIN : 'validateMpin',
  Session_Expire : 'sessionExpired'
};
